# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 691abc7c62ed4d2a78cdb7d7bf497c60433d54815ee25e7c50d5f490429ad7deec25ac86fce468a231ebfa89ea73437a9ebdf558b2bdc9bee68bb1019c89751e

test:
  secret_key_base: d8a816d1954063ddb6b25bb8fb2245c730ff5092b67cb9be1fac0fa7579928cff4ce2b19de567b2436ee8c9d6bc94388e6682260dcbb7b844c5557a1d3b6df27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
